"""
Randomized Benchmarking for Gate Fidelity Characterization

This module implements randomized benchmarking (RB) protocols for characterizing
average gate fidelities in quantum systems. RB provides a robust, scalable way
to benchmark gate performance that is insensitive to state preparation and
measurement (SPAM) errors.

Key Features:
- Single-qubit Clifford group sampling
- RB sequence generation with recovery gates
- Decay curve fitting and fidelity extraction
- Interleaved RB for specific gate characterization
- Comparison with quantum process tomography

Mathematical Framework:
- Average sequence fidelity: F_seq(m) = A·p^m + B
- Average gate fidelity: F_avg = 1 - (1-p)(d-1)/d where d=2 for qubits
- Gate infidelity: r = 1 - F_avg

References:
- Knill et al., PRA 77, 012307 (2008) - Original RB protocol
- Magesan et al., PRL 109, 080505 (2012) - Scalable RB theory
- Magesan et al., PRL 106, 180504 (2011) - Interleaved RB
"""

import numpy as np
import qutip as qt
from dataclasses import dataclass
from typing import List, Tuple, Dict, Optional, Callable, Union
from scipy.optimize import curve_fit
from scipy.linalg import expm
import warnings


@dataclass
class RBResult:
    """Results from randomized benchmarking experiment.

    Attributes:
        sequence_lengths: Array of sequence lengths tested
        survival_probabilities: Measured survival probability for each length
        fit_parameters: Fitted parameters (A, p, B) from decay curve
        average_fidelity: Extracted average gate fidelity
        gate_infidelity: Gate error rate r = 1 - F_avg
        std_error: Standard error in fidelity estimate
        metadata: Additional experiment metadata
    """

    sequence_lengths: np.ndarray
    survival_probabilities: np.ndarray
    fit_parameters: Dict[str, float]
    average_fidelity: float
    gate_infidelity: float
    std_error: Optional[float] = None
    metadata: Optional[Dict] = None

    def __repr__(self):
        return (
            f"RBResult(F_avg={self.average_fidelity:.6f}, "
            f"r={self.gate_infidelity:.2e}, "
            f"p={self.fit_parameters['p']:.6f})"
        )


class CliffordGroup:
    """Single-qubit Clifford group operations.

    The single-qubit Clifford group has 24 elements, generated by:
    - Hadamard: H
    - Phase gate: S = diag(1, i)
    - Pauli gates: X, Y, Z

    All Clifford operations can be decomposed as products of these generators.
    """

    def __init__(self):
        """Initialize Clifford group generators."""
        # Pauli operators
        self.I = qt.qeye(2)
        self.X = qt.sigmax()
        self.Y = qt.sigmay()
        self.Z = qt.sigmaz()

        # Clifford generators
        self.H = qt.gates.hadamard_transform()  # Hadamard
        self.S = qt.gates.phasegate(np.pi / 2)  # Phase gate (√Z)

        # Generate all 24 Clifford elements
        self._clifford_gates = self._generate_clifford_group()

    def _generate_clifford_group(self) -> List[qt.Qobj]:
        """Generate all 24 single-qubit Clifford gates.

        Uses the fact that Cliffords map Paulis to Paulis under conjugation.
        """
        cliffords = []

        # Identity and Paulis (4 elements)
        paulis = [self.I, self.X, self.Y, self.Z]

        # Powers of S (S^0, S^1, S^2, S^3) combined with H
        # This generates representatives of all 24 Cliffords
        for i in range(4):  # S^i
            for j in range(2):  # H^j
                for k in range(3):  # S^k after H
                    gate = self.I
                    # Apply S^i
                    for _ in range(i):
                        gate = self.S * gate
                    # Apply H^j
                    if j == 1:
                        gate = self.H * gate
                    # Apply S^k
                    for _ in range(k):
                        gate = self.S * gate

                    # Check if this is a new Clifford (up to global phase)
                    is_new = True
                    for existing in cliffords:
                        # Two unitaries are equivalent up to global phase if
                        # their inner product has |<U|V>| = dimension
                        overlap = np.abs((gate.dag() * existing).tr())
                        if np.abs(overlap - 2) < 1e-10:
                            is_new = False
                            break

                    if is_new and len(cliffords) < 24:
                        cliffords.append(gate)

        # If we didn't get all 24, use explicit construction
        if len(cliffords) < 24:
            cliffords = self._explicit_clifford_construction()

        return cliffords[:24]  # Ensure exactly 24

    def _explicit_clifford_construction(self) -> List[qt.Qobj]:
        """Explicit construction of all 24 Clifford gates."""
        C = []

        # Group 1: I, X, Y, Z (4 gates)
        C.extend([self.I, self.X, self.Y, self.Z])

        # Group 2: Hadamard-like (4 gates)
        C.extend([self.H, self.H * self.X, self.H * self.Y, self.H * self.Z])

        # Group 3: S and variants (8 gates)
        C.extend(
            [
                self.S,
                self.S * self.X,
                self.S * self.Y,
                self.S * self.Z,
                self.S * self.H,
                self.S * self.H * self.X,
                self.S * self.H * self.Y,
                self.S * self.H * self.Z,
            ]
        )

        # Group 4: Additional combinations (8 gates)
        C.extend(
            [
                self.H * self.S,
                self.H * self.S * self.X,
                self.H * self.S * self.Y,
                self.H * self.S * self.Z,
                self.S * self.S * self.H,
                self.S * self.S * self.H * self.X,
                self.S * self.S * self.H * self.Y,
                self.S * self.S * self.H * self.Z,
            ]
        )

        return C[:24]

    def get_random_clifford(self) -> qt.Qobj:
        """Sample a random Clifford gate."""
        idx = np.random.randint(0, len(self._clifford_gates))
        return self._clifford_gates[idx]

    def get_clifford(self, index: int) -> qt.Qobj:
        """Get specific Clifford gate by index (0-23)."""
        if not 0 <= index < 24:
            raise ValueError(f"Clifford index must be 0-23, got {index}")
        return self._clifford_gates[index]

    def find_inverse(self, clifford: qt.Qobj) -> qt.Qobj:
        """Find the inverse Clifford gate (up to global phase)."""
        target = clifford.dag()

        # Find matching Clifford
        for c in self._clifford_gates:
            overlap = np.abs((target.dag() * c).tr())
            if np.abs(overlap - 2) < 1e-10:
                return c

        # If not found, return dagger (should always find one)
        return target

    def compose_cliffords(self, clifford_list: List[qt.Qobj]) -> qt.Qobj:
        """Compose a list of Clifford gates."""
        result = self.I
        for c in clifford_list:
            result = c * result
        return result

    @property
    def num_cliffords(self) -> int:
        """Number of Clifford gates."""
        return len(self._clifford_gates)


class RBSequenceGenerator:
    """Generate randomized benchmarking sequences.

    Generates random Clifford sequences with recovery gates such that
    the ideal sequence implements the identity operation.
    """

    def __init__(self, clifford_group: Optional[CliffordGroup] = None):
        """Initialize RB sequence generator.

        Args:
            clifford_group: CliffordGroup instance (creates new if None)
        """
        self.clifford_group = clifford_group or CliffordGroup()

    def generate_sequence(
        self, length: int, return_recovery: bool = True
    ) -> Tuple[List[qt.Qobj], Optional[qt.Qobj]]:
        """Generate a single RB sequence.

        Args:
            length: Number of Clifford gates in sequence (before recovery)
            return_recovery: If True, return recovery gate to make sequence = I

        Returns:
            (sequence_gates, recovery_gate) where recovery_gate is None if
            return_recovery=False
        """
        if length < 0:
            raise ValueError("Sequence length must be non-negative")

        # Generate random Clifford sequence
        sequence = [self.clifford_group.get_random_clifford() for _ in range(length)]

        if return_recovery:
            # Compute product of sequence
            product = self.clifford_group.compose_cliffords(sequence)
            # Find inverse to make total sequence = identity
            recovery = self.clifford_group.find_inverse(product)
            return sequence, recovery
        else:
            return sequence, None

    def generate_rb_sequences(
        self,
        sequence_lengths: List[int],
        num_samples: int = 30,
        randomize: bool = True,
    ) -> Dict[int, List[Tuple[List[qt.Qobj], qt.Qobj]]]:
        """Generate multiple RB sequences for different lengths.

        Args:
            sequence_lengths: List of sequence lengths to test
            num_samples: Number of random sequences per length
            randomize: If True, use random sequences; if False, deterministic

        Returns:
            Dict mapping length -> list of (sequence, recovery) tuples
        """
        rb_sequences = {}

        for length in sequence_lengths:
            sequences = []
            for _ in range(num_samples):
                seq, recovery = self.generate_sequence(length, return_recovery=True)
                sequences.append((seq, recovery))
            rb_sequences[length] = sequences

        return rb_sequences


class RBExperiment:
    """Run randomized benchmarking experiments.

    Simulates RB experiments by applying noisy gate implementations and
    measuring survival probability.
    """

    def __init__(
        self,
        ideal_gate_map: Optional[Dict[int, qt.Qobj]] = None,
        noisy_gate_map: Optional[Dict[int, Callable]] = None,
        initial_state: Optional[qt.Qobj] = None,
        measurement_basis: Optional[qt.Qobj] = None,
    ):
        """Initialize RB experiment.

        Args:
            ideal_gate_map: Map from Clifford index to ideal unitary
            noisy_gate_map: Map from Clifford index to noisy operation function
            initial_state: Initial state (default |0⟩)
            measurement_basis: Measurement projector (default |0⟩⟨0|)
        """
        self.clifford_group = CliffordGroup()
        self.sequence_gen = RBSequenceGenerator(self.clifford_group)

        # Default to qubit ground state
        self.initial_state = initial_state or qt.basis(2, 0)
        self.measurement_basis = measurement_basis or qt.ket2dm(qt.basis(2, 0))

        # Gate maps (if not provided, use ideal Cliffords)
        self.ideal_gate_map = ideal_gate_map
        self.noisy_gate_map = noisy_gate_map

    def simulate_sequence(
        self,
        sequence: List[qt.Qobj],
        recovery: qt.Qobj,
        noise_model: Optional[Callable] = None,
    ) -> float:
        """Simulate a single RB sequence and measure survival probability.

        Args:
            sequence: List of Clifford gates
            recovery: Recovery gate
            noise_model: Function that adds noise to each gate

        Returns:
            Survival probability (measurement in initial state basis)
        """
        # Start with initial state
        state = self.initial_state

        # Apply sequence gates
        for gate in sequence:
            if noise_model is not None:
                gate = noise_model(gate)
            state = gate * state

        # Apply recovery gate
        if noise_model is not None:
            recovery = noise_model(recovery)
        state = recovery * state

        # Measure survival probability
        if state.type == "ket":
            state_dm = qt.ket2dm(state)
        else:
            state_dm = state

        prob = np.real((self.measurement_basis * state_dm).tr())
        return np.clip(prob, 0, 1)

    def run_rb_experiment(
        self,
        sequence_lengths: List[int],
        num_samples: int = 30,
        noise_model: Optional[Callable] = None,
        add_measurement_noise: bool = False,
    ) -> RBResult:
        """Run full RB experiment across multiple sequence lengths.

        Args:
            sequence_lengths: List of sequence lengths m to test
            num_samples: Number of random sequences per length
            noise_model: Function to add noise to gates
            add_measurement_noise: Add shot noise to measurements

        Returns:
            RBResult with fitted parameters and extracted fidelity
        """
        sequence_lengths = np.array(sequence_lengths)
        survival_probs = []

        # Generate and run sequences for each length
        rb_sequences = self.sequence_gen.generate_rb_sequences(
            sequence_lengths.tolist(), num_samples
        )

        for length in sequence_lengths:
            probs = []
            for seq, recovery in rb_sequences[length]:
                prob = self.simulate_sequence(seq, recovery, noise_model)

                # Optionally add measurement noise
                if add_measurement_noise:
                    prob += np.random.randn() * 0.01  # 1% measurement noise
                    prob = np.clip(prob, 0, 1)

                probs.append(prob)

            # Average over samples
            survival_probs.append(np.mean(probs))

        survival_probs = np.array(survival_probs)

        # Fit decay curve and extract fidelity
        result = self.fit_rb_decay(sequence_lengths, survival_probs)

        return result

    def _fit_rb_curve(
        self, sequence_lengths: np.ndarray, survival_probs: np.ndarray
    ) -> tuple:
        """
        Fit RB decay curve with exponential model.

        Args:
            sequence_lengths: Array of sequence lengths
            survival_probs: Measured survival probabilities

        Returns:
            A_fit, p_fit, B_fit, p_error
        """

        def rb_decay(m, A, p, B):
            return A * p**m + B

        p0 = [0.5, 0.95, 0.5]  # Initial guess (A, p, B)

        try:
            popt, pcov = curve_fit(
                rb_decay,
                sequence_lengths,
                survival_probs,
                p0=p0,
                bounds=([0, 0, 0], [1, 1, 1]),
                maxfev=5000,
            )
            A_fit, p_fit, B_fit = popt
            perr = np.sqrt(np.diag(pcov))
            p_error = perr[1]
            return A_fit, p_fit, B_fit, p_error

        except Exception as e:
            warnings.warn(f"RB curve fitting failed: {e}. Using fallback.")
            return self._fallback_rb_fit(sequence_lengths, survival_probs)

    def _fallback_rb_fit(
        self, sequence_lengths: np.ndarray, survival_probs: np.ndarray
    ) -> tuple:
        """
        Fallback RB fit using linear fit in log space.

        Args:
            sequence_lengths: Array of sequence lengths
            survival_probs: Measured survival probabilities

        Returns:
            A_fit, p_fit, B_fit, p_error
        """
        valid_idx = survival_probs > 1e-10
        if np.sum(valid_idx) > 2:
            log_probs = np.log(np.maximum(survival_probs[valid_idx], 1e-10))
            poly = np.polyfit(sequence_lengths[valid_idx], log_probs, 1)
            p_fit = np.exp(poly[0])
        else:
            p_fit = 0.9

        return 0.5, p_fit, 0.5, 0.05

    def _compute_gate_fidelity(self, p_fit: float, p_error: float, d: int = 2) -> tuple:
        """
        Compute average gate fidelity from depolarizing parameter.

        Args:
            p_fit: Fitted depolarizing parameter
            p_error: Error in p
            d: Dimension (default 2 for single qubit)

        Returns:
            F_avg, gate_infidelity, F_error
        """
        F_avg = 1 - (1 - p_fit) * (d - 1) / d
        gate_infidelity = 1 - F_avg
        F_error = p_error * (d - 1) / d
        return F_avg, gate_infidelity, F_error

    def fit_rb_decay(
        self, sequence_lengths: np.ndarray, survival_probs: np.ndarray
    ) -> RBResult:
        """Fit RB decay curve and extract average gate fidelity.

        The RB decay curve is: F_seq(m) = A·p^m + B
        where p is the depolarizing parameter related to average fidelity.

        Args:
            sequence_lengths: Array of sequence lengths
            survival_probs: Measured survival probabilities

        Returns:
            RBResult with fit parameters and fidelity
        """
        # Fit RB curve
        A_fit, p_fit, B_fit, p_error = self._fit_rb_curve(
            sequence_lengths, survival_probs
        )

        # Compute gate fidelity
        d = 2  # dimension
        F_avg, gate_infidelity, F_error = self._compute_gate_fidelity(p_fit, p_error, d)

        fit_params = {"A": A_fit, "p": p_fit, "B": B_fit}

        return RBResult(
            sequence_lengths=sequence_lengths,
            survival_probabilities=survival_probs,
            fit_parameters=fit_params,
            average_fidelity=F_avg,
            gate_infidelity=gate_infidelity,
            std_error=F_error,
            metadata={"dimension": d, "num_cliffords": 24},
        )


class InterleavedRB:
    """Interleaved randomized benchmarking for specific gate characterization.

    Interleaved RB measures the fidelity of a specific target gate by
    comparing standard RB with RB where the target gate is interleaved
    between random Cliffords.
    """

    def __init__(self, clifford_group: Optional[CliffordGroup] = None):
        """Initialize interleaved RB.

        Args:
            clifford_group: CliffordGroup instance
        """
        self.clifford_group = clifford_group or CliffordGroup()
        self.rb_experiment = RBExperiment()

    def generate_interleaved_sequence(
        self, length: int, target_gate: qt.Qobj
    ) -> Tuple[List[qt.Qobj], qt.Qobj]:
        """Generate interleaved sequence: C_1, G, C_2, G, ..., C_m, G, recovery.

        Args:
            length: Number of random Cliffords (target gate interleaved between)
            target_gate: Target gate to characterize

        Returns:
            (interleaved_sequence, recovery_gate)
        """
        sequence = []
        product = self.clifford_group.I

        for _ in range(length):
            # Random Clifford
            clifford = self.clifford_group.get_random_clifford()
            sequence.append(clifford)
            product = clifford * product

            # Interleaved target gate
            sequence.append(target_gate)
            product = target_gate * product

        # Find recovery gate
        recovery = self.clifford_group.find_inverse(product)

        return sequence, recovery

    def run_interleaved_rb(
        self,
        target_gate: qt.Qobj,
        sequence_lengths: List[int],
        num_samples: int = 30,
        noise_model: Optional[Callable] = None,
    ) -> Tuple[RBResult, RBResult, float]:
        """Run interleaved RB to characterize target gate fidelity.

        Args:
            target_gate: Gate to characterize
            sequence_lengths: Sequence lengths to test
            num_samples: Number of samples per length
            noise_model: Noise model to apply

        Returns:
            (standard_rb_result, interleaved_rb_result, target_gate_fidelity)
        """
        # Standard RB
        standard_result = self.rb_experiment.run_rb_experiment(
            sequence_lengths, num_samples, noise_model
        )

        # Interleaved RB
        interleaved_survival = []
        for length in sequence_lengths:
            probs = []
            for _ in range(num_samples):
                seq, recovery = self.generate_interleaved_sequence(length, target_gate)
                prob = self.rb_experiment.simulate_sequence(seq, recovery, noise_model)
                probs.append(prob)
            interleaved_survival.append(np.mean(probs))

        interleaved_survival = np.array(interleaved_survival)
        interleaved_result = self.rb_experiment.fit_rb_decay(
            np.array(sequence_lengths), interleaved_survival
        )

        # Extract target gate fidelity
        # F_gate = 1 - (1 - p_interleaved/p_standard) * (d-1)/d
        p_standard = standard_result.fit_parameters["p"]
        p_interleaved = interleaved_result.fit_parameters["p"]

        d = 2
        if p_standard > 0:
            F_gate = 1 - (1 - p_interleaved / p_standard) * (d - 1) / d
        else:
            F_gate = 0.0

        return standard_result, interleaved_result, F_gate


def depolarizing_noise(gate: qt.Qobj, error_rate: float) -> qt.Qobj:
    """Apply depolarizing noise to a gate.

    The depolarizing channel with error rate r is:
    ρ → (1-r)UρU† + r·I/d

    For unitary simulation, we approximate via Kraus operators.

    Args:
        gate: Ideal gate unitary
        error_rate: Depolarizing error rate

    Returns:
        Noisy gate (superoperator or averaged unitary)
    """
    if error_rate == 0:
        return gate

    # For unitary simulation, we can't directly apply a channel
    # Instead, return the ideal gate and apply noise separately
    # This is a placeholder - full simulation would use density matrices

    # Random Pauli error approximation
    if np.random.rand() < error_rate:
        # Apply random Pauli
        pauli = np.random.choice([qt.sigmax(), qt.sigmay(), qt.sigmaz()])
        return pauli * gate * pauli.dag() * gate
    else:
        return gate


def amplitude_damping_noise(gate: qt.Qobj, T1: float, gate_time: float) -> qt.Qobj:
    """Apply amplitude damping noise during gate.

    Args:
        gate: Ideal gate unitary
        T1: Amplitude damping time
        gate_time: Gate duration

    Returns:
        Gate with amplitude damping
    """
    gamma = 1 - np.exp(-gate_time / T1)

    # For unitary simulation, approximate by randomly applying relaxation
    if np.random.rand() < gamma:
        # Apply lowering operator
        return qt.destroy(2) * gate
    else:
        return gate


def visualize_rb_decay(
    rb_result: RBResult, ax: Optional[object] = None, show_fit: bool = True
) -> object:
    """Visualize RB decay curve with fit.

    Args:
        rb_result: RBResult from experiment
        ax: Matplotlib axes (creates new if None)
        show_fit: Show fitted decay curve

    Returns:
        Matplotlib axes
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        raise ImportError("matplotlib required for visualization")

    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 6))

    lengths = rb_result.sequence_lengths
    probs = rb_result.survival_probabilities

    # Plot data
    ax.plot(lengths, probs, "o", markersize=8, label="Measured", color="blue")

    # Plot fit
    if show_fit:
        A = rb_result.fit_parameters["A"]
        p = rb_result.fit_parameters["p"]
        B = rb_result.fit_parameters["B"]

        m_fit = np.linspace(lengths[0], lengths[-1], 100)
        fit_curve = A * p**m_fit + B
        ax.plot(m_fit, fit_curve, "-", linewidth=2, label="Fit", color="red")

    ax.set_xlabel("Sequence Length m", fontsize=12)
    ax.set_ylabel("Survival Probability", fontsize=12)
    ax.set_title(
        f"Randomized Benchmarking\nF_avg = {rb_result.average_fidelity:.6f}, "
        f"r = {rb_result.gate_infidelity:.2e}",
        fontsize=14,
    )
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)

    return ax
