name: Notebooks

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'notebooks/**'
      - 'src/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'notebooks/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  validate-notebooks:
    name: Validate Notebooks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - "01_basic_pulse_design.ipynb"
          - "02_grape_optimization.ipynb"
          - "03_noise_robustness.ipynb"
          - "04_advanced_pulse_shaping.ipynb"
          - "05_gate_optimization.ipynb"
          - "06_robustness_analysis.ipynb"
          - "07_visualization_gallery.ipynb"
          - "08_end_to_end_workflow.ipynb"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib jupyter nbconvert nbformat ipykernel
        pip install qutip>=4.7.0
        pip install pytest  # For any test utilities notebooks might use

    - name: Execute notebook ${{ matrix.notebook }}
      run: |
        if [ -f "notebooks/${{ matrix.notebook }}" ]; then
          echo "Executing notebooks/${{ matrix.notebook }}"
          jupyter nbconvert --to notebook --execute \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            --output-dir=/tmp/notebook-outputs \
            notebooks/${{ matrix.notebook }}
        else
          echo "Notebook notebooks/${{ matrix.notebook }} not found, skipping..."
          exit 0
        fi
      timeout-minutes: 15

    - name: Upload executed notebook
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: executed-${{ matrix.notebook }}
        path: /tmp/notebook-outputs/${{ matrix.notebook }}
        retention-days: 7

  notebook-summary:
    name: Notebook Execution Summary
    runs-on: ubuntu-latest
    needs: validate-notebooks
    if: always()

    steps:
    - name: Report results
      run: |
        echo "Notebook validation workflow completed"
        echo "Check individual job results for details"
